var GAME_LEVELS = [
  ["x                                                                                ",
   "x                                                                                ",
   "x                                                                                ",
   "xxx                                                                              ",
   "xvx                                                                              ",
   "x x                                                                              ",
   "x x                                                                              ",
   "x x                                                                              ",
   "x x                                                      x    e   x              ",
   "x x                                             q        xxxxxxxxxx          q   ",
   "x x                                          xxxxxxx                      xxxxxxx",
   "x x                                 q                                        x v ",
   "x x                   q           xxxxx                                      x   ",
   "x x                xxxxxxx                                                   x   ",
   "x x                                      xxx                            x    x   ",
   "x x           xx            xx            xx                            x    x   ",
   "x x  @        xx      e     xx      e     xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!x e  x   ",
   "x!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxx   ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxx!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],

  ["                                                                                                                xx",
   "                                                                                                                xx",
   "                                                                                                                xx",
   "                             q                      q                                                           xx",
   "                       xxxxxxxxxxxx             xxxxxxxxxxxx                                                    xx",
   "                    xxxxxxx!!!                       !!!xxxxxxxx                                                xx",
   "                 xxxxxxxxx!!!!           q           !!!!xxxxxxxxxx       xxxxxxx                xxx            xx",
   "                xxxxxxxxx!!!!!          xxx          !!!!!xxxxxxxxxx                              xx      e     xx",
   "         xxx     xxxxxxxxx!!!!          xxx          !!!!xxxxxxxxxx                 xxxx   xxxx   xx!!xxxxxxxx!!xx",
   " @                   xxxxxxxxx    e     xxx    e     xxxxxxxxxx                                   xx!!xxxxxxxx!!xx",
   "    q                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                          xxxxxxxxxxxxxxxx",
   "xxxxxx                           xxxxxxxxxxxxxxxxxx                                               xxxxxxxxxxxxxxxx",
   "xxxxxxx                                                                     xxxx                  xxxxxxxxxxxxxxxx",
   "xxxxxxxx                                                                                          xxxxxxxxxxxxxxxx",
   "xxxxxxxxx!                                                                                        xxxxxxxxxxxxxxxx",
   "xxxxxxxxx!!x                                         xxxx     =    xxxx                           xxxxxxxxxxxxxxxx",
   "xxxxxxxxx!!xxxx                xx          e         xxxx          xxxx                                      |  xx",
   "xxxxxxxxxx!!!xxxxxx       =  xxxxxxxxxxxxxxxxxxxxxxxxxxxx    e     xxxx                                         xx",
   "!!!!!xxxxx!!!!xxxxxxxxxxx      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                         xx",
   "!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    qxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxx"],

  ["                                                                                                          x",
   "                                                                                                          x",
   "                                      xxxxxxxxxxxxx                                                       x",
   "                                    xx             xxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "                                xxxx                         xxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "                         xxxxxxx                                           xxxxxxxxxxxxxxxxxxxxx!xx!!!!!!!x",
   "!!!!!!!!!!!!!!!!!!!!!!!!x                                                                       v  xxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!x                                                                                  x",
   "!!!!!!!!!!!!!!!!!!!!xxx                                                                                   x",
   "!!!!!!!!!!!!!!!!!!xx                                                                                      x",
   "!!!!!!!!!!!!!!!!xx                             x   e    x                                                 x",
   "!!!!!!!!!!!!!!!x                               xxxxxxxxxx                                                 x",
   "!!!!!!!!!!!!!!x                                          xx                                               x",
   "!!!!!!!!!!!!!x                       xxxx                                q                                x",
   "!!!!!!!!!!!xx                                                    xx     xxx         x                x    x",
   "!!!!!!!!!!x                  xx                                         xxx  xxxx   x       xxx      x    x",
   "!!!!!!!!!!x                  xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!x    x",
   "!!!!!!!!!x               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xx",
   "!!!!!!!!!x                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    x",
   "!!!!!!!!!x           xx    xxxxxxxxxx!!xxxxxxxxx!!!xxxxxxxx!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!xx    x",
   "!!!!!!!!xx                 xxxxxxxxx!!!x!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!xxxx!!!!!!!!!!!!!!!!!!!!!!xxx    x",
   "!!!!!!xxx      xxx         x!!!!!!!!!!!x!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!xxxxxx!!!!!!!!!!!!!!!!!!!!xxxx!x   xx",
   "!!!!!xxxx                  x x!!!!xx!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!xxxxxxxxxx    x",
   "!!xxxxxxx                  x xxxxxxx!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx    x",
   "xxxxxxxxxxx                        x!!!x!!!!!!!!!!!x!!!!!!!!!!!x!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x    x",
   "x                   xxxx           x!!!x!!!!!!!!!!!xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x   xx",
   "x                           |      x!!!xx!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!x    x",
   "x                                  x!!!x!!!!!!!!!!xx!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x    x",
   "x    x    e    x                   x!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx    x",
   "x    xxxxxxxxxxx           x   e   xx!!!xxxxxxxxxxxx!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!xvxxxxxxxxxxx       xx",
   "x            v             xxxxxxxxxxx!!!xxxxxxxxxx!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!x        xxxx q      x",
   "x                          xxxx!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!xx           x        x",
   "xxxxx              xx      xxxxx!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx           xxxxxx    x",
   "xxxxx                      xxxxxxx!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x   xxxxxxxxxxxxx    x",
   "xxxxx                      xxxxxxxxx!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx  x   xxxxxxxxxx    x",
   "xxxxx                  q   xxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!xxxxx!!!!!!!!!!!xx            xx    x",
   "xxxxxxx               xxx  xxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!x               x   xx",
   "xxxxx                      xxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!x!x!x!!!!!!!!!!x               x    x",
   "xxxxx              x       xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!xxx!xxx!!!!!!!!!!!xx            xx    x",
   "xxxxx     q        x!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!xxx!!!!!xxxxx   xxxxxx    x",
   "xxxxx    xxx       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!x!!!!!!!!!!!!!xxxxxxxxx   xx",
   "xxxxx                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xx",
   "xxxxx                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            x",
   "xxxxx           @          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            x",
   "xxxxx!!!!!!!!!xxxxx!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       x    x",
   "xxxxx!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  e    x    x",
   "xxxxx!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],

  ["!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!                            !",
   "!   xxx   xx    xx   xxx   x !",
   "!  x     x  x  x  x  x  x  x !",
   "!  x     x  x  x  x  x  x  x !",
   "!  x xx  x  x  x  x  x  x  x !",
   "!  x  x  x  x  x  x  x  x    !",
   "!   xx    xx    xx   xxx   x !",
   "!                            !",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"]

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
